apiVersion: v1
appVersion: "419"
description: High performance, distributed SQL query engine for big data
name: trino
version: 5.3.2
kubeVersion: ">= 1.24.0-0 < 1.28.0-0"
home: https://trino.io
icon: https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg
sources:
  - https://github.com/valeriano-manassero/helm-charts
  - https://github.com/trinodb/trino
maintainers:
  - name: valeriano-manassero
    url: https://github.com/valeriano-manassero
keywords:
  - trino
  - trinosql
  - trinodb
  - presto
  - prestosql
  - prestodb
  - "big data"
  - database
  - sql
  - "query engine"
  - "high performance"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Password authenticator properties
    - kind: added
      description: Pod labels
    - kind: added
      description: Fix container env. Added container envFrom
    - kind: Fixed
      description: fix password authentication secret generation when multiple auth types configured